language: android

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

jdk:
  - oraclejdk7

env:
  global:
    - TERM=dumb
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
    - secure: "XZQQHBBZ2VNEMTlzu/wNgqpbxIEU97FdGBUS2UZQ+8FPMNh4V3HUQVA8XyWwoT3WevHGu1saaViHJp8cq1PqqsJktNJVsczYMvCIvL0hQYri9PbMOamLLxj3bl/Mt5Wzcy1NC9ArzzOtIk/8muSyULPYEMM9Nt5TmPaZwawttuh0nngNdgTpRxXFC5hRhzv6e+HdZ6/23zofOFM2FiSpFYo6hXvzpw7mbYSDBYdeNe2JdxpdQidXTRzvvPTejhCzmUy+QYF2v6+XI3HUwNiMxrA8EezoTESiRADff99DJfbb5v/0raP34/hyMUioJeEZn9NYFEN2v4oOCR/Qse49eDDmgrZSbdyyPQJncMSTGSnqCQaOp5Ss4r2BYDCEyndfYYNiUWHa2RhauD4/ltz6atGN5tojwLsHt0fl2AegRW+EIkqnAyi+4Zqk4J4+H/PW2gJM8+wO6YiJS0qDrGwmv71fVtkbuWErZYw6MomN9/9h+i+0R2zgIKc78LLw0VFk74RdEBhlqIPsvrU6ICsYUeeXIf887sr5gF8nZUAs3Ia8SJOovNMCfDw2ht0BbnN8TvjaQu8yLCpRJxnpvqBYj+ZPCvM+DADeWzyagPtfmwYlGQLrhhNQ0aEVP1bZ0ppvUHhCsRK3PyJn0oaYUInKiAKnTysD2UKXYRTJJ2fWwEo="
    - secure: "dvrrP1cdYfsKLJIqdkhgEJdoVdTEx1P+1TWOs4caPlmHiFN8epaWJ0XdEP5ZuR6ntt0cIBBeqIHKjhlkfCqjoJ+TwAo66yhxc9Zj5Ka+G+H0KKiN0gK8yXKFQ01/ydxFyiId2wTBEZcHpHBVpV22a+uviEg9Z3d3sLtatnPw1Uc7LmkEYcS9wcu/cx03eJwK3Pc1boS6Is/GzRVonqg0nUuu/4QLFiLEWAIqPI2/G+McpaI1BUTKeRAUYxYikNYVqYdw+6OFI/JEu0rxO3qIvPTI8UDz/VTopO0T2eLnJwt66rXGIqh+LW67uKm5HxeYu6EOv827ZSObM8xwu9NqG3iU9tB6AUcPGm8FY04xFvKMgfVgh3wbG6viOm2aM0e8iQ5iwMxG0BeenQxIXRrxiDmnvn6m7+QyPnDVqme84xtCbk5F+PJ7Ul+AhQUdKSuyYCHlvYNdEpblXaH7H01b4CyQ6izQ9PSKug9ZhzOMBKPje/uGwOlEQSrQyR+jh+TUmoElZNxz2AsivSnHhi0yaoHNyLlJGZAgPV46dygfwwOOm/jo3kRFlE7h1zp5kNYnVb77mV4krtE/+DBU6MI8IMOZHg7DiReGVc4Xp3AogYr7m4gFrpTCf8uo4Bfac35d2g3yKNY8hKWAmu//F4jyRT0x/MFQGtCIJimJ+ChQvN0="

android:
  components:
    - build-tools-23.0.1
    - android-23
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'

install: /bin/true

script: ./gradlew build

deploy:
  - provider: script
    script: scripts/bintrayUpload.sh
    skip_cleanup: true
    on:
      tags: true
